### ISSUE TITLE
Finir de nettoyer jardin/roadmap

### ISSUE THREAD

**Issue by penelopel** [betagouv/territoires-en-transitions#1315]
- [x] redécouper la #975 
- [x] Remettre dans les bonnes colonnes ce qui est vraiment prêt et/ou qui nécessite un travail métier/design
- [x] Tagger avec les buckets
- [x] Rajoute les P2 dans la roadmap
