### ISSUE TITLE
EPIC - Je peux gérer les caractéristiques de la collectivité pour personnaliser le référentiel

### ISSUE THREAD

**Issue by penelopel** [betagouv/territoires-en-transitions#1372]
En tant que personne référente d’une collectivité, je veux valider ou préciser les caractéristiques de ma collectivité afin de personnaliser de manière fiable le contenu de l’application (actions concernées et potentiel de points)

Les collectivités ont chacune des caractéristiques et compétences : le référentiel s'adapte à celles-ci pour que la collectivité ne soit concernée que par des actions/tâches sur lesquelles elle peut réellement agir / avoir un pouvoir d'action ou d'influence. 
Une part de ces caractéristiques et compétences peuvent être automatisables via des bases de donnés (INSEE, Banatic...), d'autres sont à compléter par la collectivité.

Cas 1 - A l'association du profil de la collectivité pour la première par un utilisateur (supposé être le chef de projet de la collectivité) : 
- [ ] Création d'un formulaire reprenant une carte d'identité (avec données issues d'autres BdD) et des questions (compétences et autres caractéristiques pour lesquelles les bases de données n'existent pas ou sont peu fiables)
- [ ] Association automatique des caractéristiques et des compétences renseignées avec les réductions de potentiel (statut "non concerné" ou nombre max de points sur tâches/sous-actions/actions)

Maquette : 

Cas 2 - Depuis la page dédiée aux caractéristiques et compétences, pour le chef de projet (après recherche des infos auprès d'autres agents/services) ou une personne spécifique (agent particulier "urbanisme" par exemple)
- [ ] Même formulaire que cas 1, mais avec les infos et liens vers les actions concernées par les réductions de potentiel pour faciliter la navigation

Maquette : 

Cas 3 - Lors de l'utilisation du référentiel
- [ ] Directement au niveau de l'action/sous-action ou tâche, création d'un bouton pour changer le potentiel avec information sur les conditions de réduction du potentiel et le formulaire pour modifier la caractéristique ou compétence 

Listes des critères : https://docs.google.com/spreadsheets/d/1179r5h7wsN9LXySx-fhzYJho2w2nU-tg6_ErFBGVI0c/edit?usp=sharing  (*Onglet : Caractéristiques règles finales*)
Maquettes : 
[Proposition de maquette (1. et 2.)](https://www.figma.com/file/YhEoPD2YxqHuEaPn8nKWql/Maquettes-2k22?node-id=187%3A14865)

[Ajout d'un bouton pour 3.](https://www.figma.com/file/YhEoPD2YxqHuEaPn8nKWql/Maquettes-2k22?node-id=186%3A14408)

**Comment by cami-na** [comment]
### Validation et précision des caractéristiques de ma collectivité

En tant que personne référente d’une collectivité, je veux valider ou préciser les caractéristiques de ma collectivité afin de personnaliser de manière fiable le contenu de l’application (actions concernées et potentiel de points)

**Infos métier**

Les collectivités ont chacune des caractéristiques 
- Compétences (environ 24 dans 6 domaines + environ 12 en cas de transfert de compétences à filtrer selon le type de collectivité)
- Informations sur la démographie et la géographie (6)
- Cas spécifiques (environ 10)

Une partie de ces caractéristiques peut être identifiée automatiquement en associant la collectivité à des bases de données. 

Pour que la personnalisation du contenu de l’application soit la plus fiable possible, la personne référente de la collectivité validera et précisera les caractéristiques.

- **Validation** : pour les caractéristiques identifiées automatiquement (exemple : le type de collectivité grâce à des bases de l’Insee, etc.)
- **Précisions** : pour les caractéristiques qui ne peuvent pas être identifiées automatiquement et les parts spécifiques

**Critères d’acceptation** 

1. Pendant l’onboarding  
Suite à la création de son compte, la personne référente valide et précise les caractéristiques (format questionnaire) 

2. Dans l’espace « paramètres de la collectivité » 
La personne référente peut à n’importe quel moment consulter et modifier les caractéristiques  

3. Au niveau d’une action concernée par la réduction de potentiel  
- Un lien permet d’accéder au panneau de modification des caractéristiques 
- Une alerte signale si la ou les caractéristiques liées à l’action n’ont pas été validées

**Comment by Emelinejy** [comment]
OLD : reprise Commentaire principal écrit par Pénélope le 08-02 et modifié par Nicolas le 21-02

Cette carte regroupe l'ensemble des informations des multiples cartes précédentes sur le sujet (qui ont été fermées après regroupement)

METIER - Définir l'impact des caractéristiques sur le potentiel de points (https://docs.google.com/spreadsheets/d/1179r5h7wsN9LXySx-fhzYJho2w2nU-tg6_ErFBGVI0c/edit#gid=0) -

https://github.com/betagouv/territoires-en-transitions/issues/1221

METIER - Faire la liste des questions à poser pour les caractéristiques : https://hackmd.io/@Territoires-en-transitions/BkTfmzxJ9

https://github.com/betagouv/territoires-en-transitions/issues/1395

METIER/DEV - Définir les lieux où aller chercher les informations de façon automatique (INSEE / Optigede etc.)

    Définir les caractéristiques qui peuvent être remplies automatiquement et les lieux où aller chercher ces informations (INSEE / Optigede etc.) #1394

== en commentaire, les premiers design de Maïtané pour inspiration ==

DESIGN - Faire l'interface qui permet de renseigner globalement les caractéristiques de ma collectivité de façon automatique ou manuelle (page caractéristique de la collectivité)

https://github.com/betagouv/territoires-en-transitions/issues/1396

DESIGN - Faire l'interface qui permet de renseigner au niveau d'une sous-action les caractéristiques de ma collectivité - où je peux également réduire manuellement les points - lien avec le
? - [conseiller] En tant que conseiller je peux modifier manuellement la réduction de potentiel en dehors dès règles de réduction automatiques (override) #269 Maquetter "J'ai une visibilité et la main pour modifier les point max. d'une action du référentiel si c'est autorisé par les règles de réduction de potentiel " #269 #1198
