### ISSUE TITLE
Roadmap, Story-map

### ISSUE THREAD

**Issue by Emelinejy** [betagouv/territoires-en-transitions#2130]
- [x] Actualisation de la story-map (fait / pas fait)
- [x] Repriorisation (en équipe)
- [x] "Mise en page"
     - [x] Refaire le tableau de bord "Roadmap" avec colonne 1 - les 6 prio / colonne 2 - Fait / colonne 3 - les autres prio des 6 objectifs / colonne 4 - autres diées/fonctionnalités
     - [x] Refaire la storymaps avec 6 colonnes pour les 6 objectifs
