### ISSUE TITLE
US - Checklist de lisibilité de l'interface référentiels

### ISSUE THREAD

**Issue by penelopel** [betagouv/territoires-en-transitions#248]
#### Fonctionnel : 
- [x] Afficher les scores prévu + en cours + Pas fait (cf. US #842)
- [ ] Afficher le niveau de labellisation atteint et auquel peut prétendre la collectivité (cf US #453)
- [ ] Afficher le score manquants également sur les domaines 1 à 6 CAE (1, 2, 3, 4, 5, 6). 
#### Ergonomie : 
*Demande utilisateurs : moins scroller, vue plus compacte, vue plus en mode "tableau", visualisation du référentiel bien "structurée".*
- [x] Afficher de façon homogène sur l'ensemble de l'arborescence les jauges **de façon alignées sur une colonne à droite** avec les éléments de score en % et en points sur une seule même ligne
- [x] Remplacer les termes climat-air-énergie et économie circulaire qui prennent de la place par les logos existants comme sur la partie indicateurs
- [ ] Mettre un séparateur entre les sous-axes (cf maquette)
- [ ] Remonter les descriptions des actions en infobulle (modale?) à côté du titre pour mieux distinguer les contenus/informations fournis par les référentiels des champs sur lesquels il est attendu une saisie de contenu par l'utilisateur
- [ ] Réduire la taille de police afin de rendre plus compact réduire le besoin de scroller

#### La version repliée
![Screenshot 2021-09-17 at 11-03-18 Territoires en Transitions](https://user-images.githubusercontent.com/27999224/133756512-0656aa7b-7194-4932-adec-defee77c2392.png)

#### La version dépliée
![Screenshot 2021-09-17 at 11-03-18 Territoires en Transitions - copie](https://user-images.githubusercontent.com/27999224/133756402-baf7b79d-0f41-4472-8f3d-0cde33668423.png)

### Pages mesures/orientations : 
- [ ] Reprendre les choses de façon homogène avec la page référentiels
   - [ ] Descriptions en infobulle
   - [x] Jauges et affichage de score
   - [ ] Compacité/lisibilité
   - [ ] taille de police
- [ ] Affichage plus condensé dont une version repliée (cf. maquette) (⚠️ à rediscuter car cela doit rester incitatif pour saisir des commentaires qualitatifs lorsque l'on a mis à jour un statut

![Screenshot 2021-09-17 at 12-03-21 Territoires en Transitions](https://user-images.githubusercontent.com/27999224/133765408-e5ebeaae-f446-447f-b603-e5b242125d31.png)

### Partout : 
- [x] Arrondir les scores % et points au premier chiffre après la virgule (cf. carte #550 )
- [ ] Les flèches pour déplier ou aller vers quelque chose ne sont pas visibles/pratiques (sur indicateurs, sur les référentiels, sur le tableau de bord pour aller vers le plan d'actions). Améliorer l'ergonomie
- Proposer une alternative aux cadres "gris" et carrés. (La transition écologique c'est pas triste et avec des angles qui font mal)

### Page indicateurs : 
- [x] Mettre les champs résultats et objectifs à la suite l'un de l'autre puis le champ Commentaire
- [x] Utiliser le même affichage des descriptions que pour le référentiel
- [x] Homogénéiser les polices de titres (Résultats, Objectifs, Commentaires, Graphique)
- [ ] Renommer le titre du champ "Commentaire" afin d'encourager les personnes à apporter des précisions qualitatives.    
   - Proposition A modification du titre "Remplacer "Commentaires" par "Précisions sur l'indicateur (évolutions, sources, etc.)" 
   - Proposition B mettre un texte explicatif directement dans le champ commentaire (Ca s'appelle comment d'ailleurs "Hint?" Ca m'aiderait de connaitre le terme technique?). "Renseignez ici les informations que vous souhaitez préciser vis-à-vis de l'indicateur. Analyse de la tendance d'évolution, éléments de contexte sur l'évolution des valeurs, sources, etc."
   - Faire A+B 🤔 ?

**Comment by maiwann** [comment]
Pour cette issue, le travail initial est à mon avis de retravailler l'interface (ensemble si ça vous dit) pour qu'elle soit bien léchée :) + la #457 

J'ai retravaillé les maquettes en ce sens : 

La page mesure : ![Referentiel_mesure(1)](https://user-images.githubusercontent.com/27999224/129343714-07ac6ad4-da43-4b77-988c-2050ba0f3ce6.png)

La page référentiel :

**Comment by penelopel** [comment]
Hello !

D'un point de vue pratique pour les dev, as-tu rajouté des choses dans ces maquettes par rapport aux autres issues ? 

Du côté utilisateur, le fil d'Ariane rend effectivement plus facile le remplissage mais il me semble qu'on n'a toujours pas l'info de où j'en suis de mon remplissage du référentiel (dans le sens : j'ai bien donné les infos de 30% du référentiel, il me faut encore remplir x choses...). De ce que je comprends des maquettes, le seul indicateur que j'ai c'est que je n'ai pas le petit bloc de points qui s'affiche si je n'ai pas rempli ? 

Il faut trouver un moyen de pouvoir se rendre compte vite de là où on en est et reprendre facilement son remplissage, sans rentrer en concurrence avec les points du référentiel (ce qui est le risque des pourcentages) et surtout donner envie d'aller jusqu'au bout ;)

**Comment by maiwann** [comment]
> D'un point de vue pratique pour les dev, as-tu rajouté des choses dans ces maquettes par rapport aux autres issues ?
Non c'est surtout du changement d'interface, pas d'ajout de nouvelles fonctionnalités pour l'instant

> Il faut trouver un moyen de pouvoir se rendre compte vite de là où on en est et reprendre facilement son remplissage, sans rentrer en concurrence avec les points du référentiel (ce qui est le risque des pourcentages) et surtout donner envie d'aller jusqu'au bout ;)
Ok, j'ai besoin de faire une phase d'observation pour savoir comment bien amener ça

**Comment by maiwann** [comment]
Je transforme la carte pour qu'elle ne concerne que l'affichage, et on crée de nouvelles cartes pour les autres points

**Comment by maiwann** [comment]
@Nickvalley Est-ce qu'on peut tester d'enlever la description au niveau du référentiel ou bof ?
Si oui, ça pourrait donner ça : 
![Screenshot 2021-09-16 at 16-27-44 Territoires en Transitions](https://user-images.githubusercontent.com/27999224/133631627-cd81356c-d32e-46d4-b750-fab5b420b434.png)

**Comment by maiwann** [comment]
Et pour l'intérieur du référentiel, je propose un test : 
2 états pour les actions : 
- L'un, non rempli, qui met en avant le titre (+ les points) et la barre de statut à remplir
- Le second, rempli, qui met en avant le titre + les points

Et on peut les déplier pour voir les autres éléments : 
- (statut d'avancement dans le second cas)
- bouton fiche action
- champ à déplier (description, commentaire…)

Ca nous permet : 
- D'avoir un visuel différent selon si on a rempli ou non le référentiel, et donc de mettre en avant la barre de statut si on n'a pas rempli, les points si on a rempli
- De compacter énormément le tout, et donc d'avoir une vue d'ensemble beaucoup plus facilement
- Et d'avoir une vue plus élégante aussi…

La maquette : 

![Screenshot 2021-09-16 at 17-39-10 Territoires en Transitions](https://user-images.githubusercontent.com/27999224/133643457-6092cedf-0693-49b5-b956-64b8dbe53ea9.png)
Note : Il faut prendre le petit trait à coté du 100% comme si c'était une jauge verte, j'ai pas réussi mon copier/coller :p

**Comment by Nickvalley** [comment]
> 
> 
> @Nickvalley Est-ce qu'on peut tester d'enlever la description au niveau du référentiel ou bof ?

@maiwann 
Réponse : Je suis contre le fait d'enlever la description et pour qu'elle puisse s'afficher de façon optionnelle. 

Je pense que si elle est absente 
1/ c'est une régression de fonction
2/ on arrivera pas à embarquer les utilisateurs de Cit'ergie qui (en même temps d'avoir une vue déjà plus synthétique) ont l'habitude d'avoir la possibilité d'avoir beaucoup plus d'infos sur la vue de synthèse en option. 

Donc je suis pour le fait de reprendre le concept de pouvoir afficher/masquer les infos que l'on veut rendre visible comme dans l'EMT ce qui permet d'avoir une vue minimaliste par défaut (et l'utilisateur la paramètre pour voir plus et c'est enregistré dans son cache en suite pour la vue qu'il préfère utiliser (fonctionnement de l'EMT) . La vue synthétique brute pourrait contenir jusqu'à rien d'autre que le titres et les points au plus light puis avoir les options pour afficher beaucoup plus d'informations en sélectionnant ce que l'on souhaite afficher. Cf. mon illustration.

**Affichage de l'EMT avec presque rien** (N° de l'arborescence | icône mesure phare de la collectivité | Titres | points max du référentiel (max) | point max sur lesquels la collectivité est évaluée (pot) | Score réalisé (Eff) | score programmé (plan) |
_Nota : tout replié en zoom 100% sur mon 12 pouces j'arrive à voir confortablement les 7 premières mesures et toute l'arborescence des deux premiers sous-domaines du domaine 1 Climat-Air-Energie) :_ 
![image](https://user-images.githubusercontent.com/67585509/133648512-4b0fe6af-1ca7-4261-ba08-5671ca043ab8.png)

**Affichage de l'EMT avec presque tout** (S'insèrent en complément dans la vue de base dans les colonnes : Le potentiel et réalisé avant audit | Le potentiel et réalisé après audit (Avant labellisation) | Le potentiel après la CNL (Après labellisation) | L'affichage des points de réalisé et programmé)
![image](https://user-images.githubusercontent.com/67585509/133649479-6c046010-16a2-4452-bf31-0ea382d21380.png)

Et pour chaque mesure/orientation on peut afficher/cacher les informations utilisées grâce à des options d'affichage: 
- Description
- Descriptif des actions réalisées dans la mesure
- Descriptif des actions programmées dans la mesure
- Remarques du conseiller
- Echanges avec l'auditeur
- Fichiers
- ...

Je t'encourage à aller voir dans l'[EMT](https://tool.european-energy-award.org) comment ça fonctionne en termes d'UI et s'affiche car c'est plutôt bien foutu mais je pense qu'on peut faire encore bien mieux. On ne réussira l'embarquement du réseau Cit'ergie qu'une fois que notre proposition de valeur sera supérieure à celle de l'EMT sur les fonctionnalités que les utilisateurs ont l'habitude d'utiliser et qu'ils apprécient!

**Comment by Nickvalley** [comment]
> 
> 
> Et pour l'intérieur du référentiel, je propose un test :
> 2 états pour les actions :
> 
>     * L'un, non rempli, qui met en avant le titre (+ les points) et la barre de statut à remplir
> 
>     * Le second, rempli, qui met en avant le titre + les points

Les points devraient s'afficher sur toute l'arborescence :  
- de façon homogène plutôt que parfois à gauche et parfois à droite (et mon intuition c'est que c'est plus lisible à droite comme cela a été conçu sur l'EMT surtout quand on voudra rajouter les infos qui manquent pour l'instant pour gérer la labellisation et l'audit) 
- sur une seule ligne et pas sur deux lignes comme sur ces nouvelles maquettes car nous avons des retours sur le manque de synthèse et l'objectif c'est de pouvoir en afficher un maximum dans une vue synthétique sur une page pour réduire le besoin de scroll

Pour les 2 options d'affichage je trouve le concept sympa mais ça marche pas pour garder visible le statut car le 100% d'une action sans parent = Faite par contre pour le 0% y'a les possibilités suivantes : Pas faite, Prévue, En cours donc on perd la visibilité et c'est pas du tout ergonomique alors que le statut de l'action est ce qui nous intéresse dans notre concept, la note c'est ce qui en résulte et qui est la carotte pour renseigner le référentiel et obtenir le label mais ce qui nous intéresse cela reste l'avancement des actions. 
Si tu remaquettes pour afficher le programmé dans le score y'a plus qu'à trouver une solution pour distinguer explicitement l'affichage des actions "Programmées" des actions "En cours" et ça pourrait marcher. 
Sachant que le statut "En cours" comme on a commencé à voir avec les conseillers ça sera sûrement plus utile si c'est un curseur qui permet de découper ce qui est Prévu et Fait par tranches (de 10%? 🤔) sur l'action.

**Comment by Nickvalley** [comment]
Et du coup la jauge des référentiels ça pourrait être un truc qui affiche le % pas fait, le % en cours et le % terminé comme pour les jauges que tu as créées pour les plans d'actions et ça serait assez cool car on aurait un affichage homogène. Par contre du coup j'imagine qu'il faudrait des jauges un peu plus larges pour que ce soit lisible!..

**Comment by maiwann** [comment]
>  Réponse : Je suis contre le fait d'enlever la description et pour qu'elle puisse s'afficher de façon optionnelle.

Ok, je vais voir comment la re-rajouter. Je garde en tête le reste de ce que tu m'as dit, mais je vais avoir besoin de discuter précisément du tableau avec les conseillers pour savoir quel affichage ils préfèrent, si ils jouent souvent avec ou si ils ont leur affichage par défaut, ce qu'il y a dedans… je me rajoute une carte pour ça.

**Comment by maiwann** [comment]
> et mon intuition c'est que c'est plus lisible à droite

![image](https://user-images.githubusercontent.com/27999224/133750997-c30160e9-b5c2-4a4f-a6ec-3e2d0dc107af.png)

Pour l'instant à droite c'est pas top, ça marche mieux sur l'EMT parce qu'il y a le format tableau + le survol qui permet de voir où l'on en est, mais chez nous, c'est trop loin des titres pour réussir à repérer où cela est, même si je comprends que le fait que se soit un coup à droite, un coup à gauche ça soit pas le plus harmonieux et du coup un peu dérangeant…

**Comment by maiwann** [comment]
> sur une seule ligne et pas sur deux lignes comme sur ces nouvelles maquettes car nous avons des retours sur le manque de synthèse et l'objectif c'est de pouvoir en afficher un maximum dans une vue synthétique sur une page pour réduire le besoin de scroll

J'entends bien le besoin de ne pas avoir de page trop longue, cela dit attention à ne pas confondre ça avec le fait qu'il faille absolument tout condenser, on a d'abord besoin de clarté sur les éléments, et si c'est compact c'est encore mieux, mais ça ne va pas systématiquement ensemble.

Cela dit, si ça reste important d'avoir tout le temps les points au même endroit, je vais itérer. Mais pas facile de proposer un graphisme équilibré avec 3 éléments !

>  Si tu remaquettes pour afficher le programmé dans le score y'a plus qu'à trouver une solution pour distinguer explicitement l'affichage des actions "Programmées" des actions "En cours" et ça pourrait marcher.

Ok ça ça semble faisable

**Comment by maiwann** [comment]
> Et du coup la jauge des référentiels ça pourrait être un truc qui affiche le % pas fait, le % en cours et le % terminé comme pour les jauges que tu as créées pour les plans d'actions et ça serait assez cool car on aurait un affichage homogène. Par contre du coup j'imagine qu'il faudrait des jauges un peu plus larges pour que ce soit lisible!..

Alors on pourrait mais on va vite se confronter à devoir choisir si la couleur d'une jauge correspond au nombre de points ou au statut de l'action 😬

**Comment by maiwann** [comment]
Après plusieurs itérations, j'ai envie de proposer de voir la description au survol pour l'instant, et le jour où on aura plein d'infos à afficher, on verra comment on les agencera ?

Comme ça on garde des blocs assez fins : 

![image](https://user-images.githubusercontent.com/27999224/133754963-6cc9fc01-0f7d-430a-9ce5-6b390f0d0f0b.png)

**Comment by maiwann** [comment]
Eh bien à force d'itérations, voilà ma nouvelle proposition avec les jauges à droite ! 
![Screenshot 2021-09-17 at 11-03-18 Territoires en Transitions - copie](https://user-images.githubusercontent.com/27999224/133756402-baf7b79d-0f41-4472-8f3d-0cde33668423.png)

**Comment by maiwann** [comment]
Et voilà ma proposition pour la page mesure : On reprends les points sur la même ligne + la barre de statut, et on condense quand même un peu tout ça.

Est-ce que ça te semble mieux ?

![Screenshot 2021-09-17 at 12-03-21 Territoires en Transitions](https://user-images.githubusercontent.com/27999224/133765408-e5ebeaae-f446-447f-b603-e5b242125d31.png)
:

**Comment by maiwann** [comment]
Note : Je bidouille directement dans le navigateur à chaque fois, donc les jauges ne sont pas harmonisées (un coup sur 2 lignes, un coup sur une seule) mais je ne tiens pas forcément à l'un des états par rapport à l'autre. On peut tout mettre sur une ligne en attendant de discuter d'afficher les points programmés

**Comment by Nickvalley** [comment]
Du coup globalement je trouve ça mieux en termes de lisibilité 
Et dans le détail les choses qu'il faut faire : 
- Du côté CAE il manque le score sur les domaine (1, 2, 3, 4, 5, 6) qui possède un niveau de profondeur de plus que ECi
- Garder le score (% et points) sur une seule ligne (vu la remarque sur la bidouille :-) )
- % : Garder seulement un chiffre après la virgule xx,x% cela suffit
- Points : Après vérification côté CAE maintenant que ça s'affiche, je pense qu'on peut se permettre de travailler avec l'arrondi en passant tout l'affichage à 1 seul chiffre après la virgule. (xx,x/yy,x). Afficher 2 chiffres après la virgule permet simplement d'afficher les 0,07 points dans l'action "6.5.3.4 - Pérenniser et massifier la sensibilisation" dans le référentiel CAE. Donc je pense qu'on peut se permettre d'afficher les arrondis uniquement à la première décimale près 0,07 >>> 0,1 ; 0,13 >>> 0,1 (ça fait qu'on a 5000 graduations pour aller à 500 points, ça suffit 🤣 et on évite d'en avoir 50 000)
-  Je pense en effet qu'on peut supprimer le titre "Les actions" (et on a une discussion là dessus prévue qu'on peut avoir demain)

**Comment by maiwann** [comment]
J'ai basculé les remarques sur les points dans la carte dédiée #550 

Pour souvenir il s'agit de 
- % : Garder seulement un chiffre après la virgule xx,x% cela suffit
- Points : Après vérification côté CAE maintenant que ça s'affiche, je pense qu'on peut se permettre de travailler avec l'arrondi en passant tout l'affichage à 1 seul chiffre après la virgule. (xx,x/yy,x). Afficher 2 chiffres après la virgule permet simplement d'afficher les 0,07 points dans l'action "6.5.3.4 - Pérenniser et massifier la sensibilisation" dans le référentiel CAE. Donc je pense qu'on peut se permettre d'afficher les arrondis uniquement à la première décimale près 0,07 >>> 0,1 ; 0,13 >>> 0,1 (ça fait qu'on a 5000 graduations pour aller à 500 points, ça suffit 🤣 et on évite d'en avoir 50 000)
