### ISSUE TITLE
Retour de test 27-10-2021

### ISSUE THREAD

**Issue by Emelinejy** [betagouv/territoires-en-transitions#820]
- [x] #720 : le calcul de la complétude n'est pas bon. Si toutes les  sont renseignées, le taux devrait être de 100 %.
Ex : https://sandbox.territoiresentransitions.fr/collectivite/bac_bal_aere/action/eci/economie_circulaire__4.1
Toutes les tâches ayant un statut (NC, Pas fait, Prévue, En cours, Faite), ça devrait afficher 100 % et non 64 % . La complétude affichée ne semble pas prendre en compte NC et Pas fait

- [x] #740 : Si j'ajoute un indicateur personnalisé depuis la fiche-action, cela me dit qu'il est bien enregistré mais il ne s'affiche pas directement sur la fiche-action alors qu'il devrait apparaitre de suite (mais il est bien ajouté dans la page "Mes indicateurs") 

- [x] #720 : Il manque la complétude et les scores (points/%) sur les 6 axes du référentiel CAE (OK pour référentiel global, et sous-axe)
